### ISSUE TITLE
ABA_Matrix dimension mismatch for sparse matrix and axes

### ISSUE THREAD

**Issue by akody** [NREL-Sienna/PowerNetworkMatrices.jl#87]
When running "PNM.ABA_Matrix(sys)" specifically for the RTS GMLC test network, I get a mismatch in the size of the sparse matrix and the length of the axes. See screenshot.
![Screenshot 2024-09-16 at 9 54 54 PM](https://github.com/user-attachments/assets/d0b94c67-1b1b-48b6-bdd1-275d17078542)

**Comment by jd-lara** [comment]
@akody this is expected since the ABA matrix doesn't have the slack bus. Indexing is allowed but it will return an error.

<img width="734" alt="image" src="https://github.com/user-attachments/assets/ce4240cf-125f-4867-b6b0-04d1a8692708">

**Comment by akody** [comment]
@jd-lara According to the struct description of ABA_Matrix [here](https://github.com/NREL-Sienna/PowerNetworkMatrices.jl/blob/0ba509b9527e54a9949d0ffb9ef52d6539dd8580/src/BA_ABA_matrices.jl#L58), the field "axes" is a "Tuple containing two identical vectors, both containing the number of each bus of the network (each one related to a row/column of the Matrix in "data"), excluding the slack buses."

However, in my example, ABA_Matrix.axes does not contain vectors with the same number of rows/columns as ABA_Matrix.data, and the vectors in ABA_Matrix.axes contain the reference bus.

Let me know if I am misunderstanding something here. 

Note: It looks like there are separate ACBusTypes for SLACK and REF; however, ABA_Matrix(.) seems to remove the REF buses using functions calculate_A_matrix(.) and find_slack_positions(.)

<img width="728" alt="Screenshot 2024-09-22 at 2 05 20 PM" src="https://github.com/user-attachments/assets/56018700-9567-49ef-b03c-1d08c5359139">

**Comment by jd-lara** [comment]
you are right, we should improve this docstring and descriptor. Up to now not many people use these matrices outside of the PTDF/LODF calculations so we haven't payed too much attention to them
